### PR TITLE
Update babel to 7.0.0 and other dependencies

### PR DESCRIPTION
**Pull request by gareys**
Updating babel to 7.0.0 now that it is out of rc status.

Noticed that some other dependencies were also available to update. Tested that the server ran to confirm nothing is broken after updates.

### CODE REVIEW

**Comment by adampash** [comment]
Thanks for the PR, @gareys! I think CircleCI must have been down when you submitted — I know this is annoying, but can you push an update to your branch to re-trigger the build? (Maybe just tweak the commit message and force push would do it?)

**Comment by gareys** [comment]
Hey @adampash, I just tweaked the commit message and force pushed, let me know if I need to do it again.

**Comment by adampash** [comment]
@gareys Ha this was my fault, Circle wasn't set up to build forked PRs. Can you try one more time? (Sorry for the hassle!!!)

**Comment by gareys** [comment]
Sorry for the delay! Just pushed up a new amended commit

**Comment by adampash** [comment]
Great, and the build + test passed! Merging. Thanks @gareys!

**Pull request merged**
